name: resource_repository_objectbox
description: ObjectBox storage for the resource_repository package.
version: 0.0.1
homepage: https://github.com/NaikSoftware/resource_repository_objectbox

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  resource_repository_storage: ^0.0.2+1
  rxdart: ^0.27.4
  synchronized: ^3.0.0+2
  worker_manager: ^4.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

objectbox:
  output_dir: src/generated